# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RaMDSS
                                 A QGIS plugin
 This is a plugin that enables fetching data that is collected from the RaM-DSS mobile application.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-01-22
        copyright            : (C) 2025 by Kevin Kiprotich
        email                : kevinkiprotich0089@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
from qgis.PyQt import QtCore
from qgis.core import QgsMessageLog

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RaMDSS class from file RaMDSS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ram_dss import RaMDSS
    return RaMDSS(iface)

debug = QtCore.QSettings().value('RAM_DSS/debug', True)
def log(message, level=0):
    if debug:
        QgsMessageLog.logMessage(message, tag="RAM_DSS", level=level)
